export type RaidBoss = {
  id: string;
  name: string;
  dexNumber: number;
  types: string[];
  category: 'Legendary' | 'Mythical' | 'Mega' | 'Dynamax' | 'Regular';
  /** Weaknesses ordered by priority (double-weak first) */
  weaknesses: { type: string; multiplier: string }[];
  /** The search string to find counters in your storage */
  counterSearch: string;
  /** Months this boss has been featured in raids (YYYY-MM format) */
  featuredMonths?: string[];
  note?: string;
};

/**
 * Current raid rotation. Update this monthly.
 * IDs listed here will appear in the "This Month" section at the top of the Raids tab.
 */
export const currentRotation = {
  month: '2026-07',
  label: 'July 2026',
  bossIds: [
    'articuno', 'zapdos', 'moltres', 'kyogre', 'solgaleo', 'kyurem',
    'shadow-palkia',
    'mega-lucario', 'mega-sceptile', 'mega-salamence', 'mega-aggron',
    'dynamax-chansey', 'dynamax-deino', 'dynamax-trubbish', 'dynamax-feebas',
  ],
};

// Sprite URL helper - uses PokeAPI official artwork
export function spriteUrl(dexNumber: number): string {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${dexNumber}.png`;
}

export const raidBosses: RaidBoss[] = [
  // ── Tier 5 Raids ───────────────────────────────────────────────────────────
  {
    id: 'articuno',
    name: 'Articuno',
    dexNumber: 144,
    types: ['Ice', 'Flying'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Rock', multiplier: '2.56x' },
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
    ],
    counterSearch: '@1rock,@2rock,@1fire,@2fire,@1electric,@2electric,@1steel,@2steel',
    featuredMonths: ['2026-07', '2026-03', '2022-07', '2020-03'],
    note: 'Double weak to Rock. Rampardos, Rhyperior, Tyranitar with Smack Down are top picks.',
  },
  {
    id: 'zapdos',
    name: 'Zapdos',
    dexNumber: 145,
    types: ['Electric', 'Flying'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Rock', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
    ],
    counterSearch: '@1rock,@2rock,@1ice,@2ice',
    featuredMonths: ['2026-07', '2026-03'],
    note: 'Rock is preferred for STAB overlap with many Ground types. Rhyperior, Rampardos, Mamoswine.',
  },
  {
    id: 'moltres',
    name: 'Moltres',
    dexNumber: 146,
    types: ['Fire', 'Flying'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Rock', multiplier: '2.56x' },
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Water', multiplier: '1.6x' },
    ],
    counterSearch: '@1rock,@2rock,@1electric,@2electric,@1water,@2water',
    featuredMonths: ['2026-07', '2026-03'],
    note: 'Double weak to Rock. Rampardos and Rhyperior dominate. Water and Electric are backup options.',
  },
  {
    id: 'kyogre',
    name: 'Kyogre',
    dexNumber: 382,
    types: ['Water'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
    ],
    counterSearch: '@1electric,@2electric,@1grass,@2grass',
    featuredMonths: ['2026-07', '2026-04'],
    note: 'Prioritize Electric (Kartana, Zekrom, Xurkitree). Grass is equally effective but fewer top options.',
  },
  {
    id: 'solgaleo',
    name: 'Solgaleo',
    dexNumber: 791,
    types: ['Psychic', 'Steel'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1ground,@2ground,@1ghost,@2ghost,@1dark,@2dark',
    featuredMonths: ['2026-07', '2026-02'],
    note: 'Many weaknesses to exploit. Reshiram, Chandelure (Ghost/Fire), Groudon, Darkrai all work.',
  },
  {
    id: 'kyurem',
    name: 'Kyurem',
    dexNumber: 646,
    types: ['Dragon', 'Ice'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1steel,@2steel,@1fighting,@2fighting,@1fairy,@2fairy,@1dragon,@2dragon',
    note: 'Many weaknesses. Steel (Metagross) and Fighting (Lucario, Terrakion) are safest. Dragon hits hard but takes SE back.',
  },

  // ── Shadow Raids ───────────────────────────────────────────────────────────
  {
    id: 'shadow-palkia',
    name: 'Shadow Palkia',
    dexNumber: 484,
    types: ['Water', 'Dragon'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1dragon,@2dragon,@1fairy,@2fairy',
    featuredMonths: ['2026-07'],
    note: 'Dragon and Fairy equally effective. Dragon counters hit hard but take SE damage back. Fairy is safer.',
  },
  {
    id: 'palkia',
    name: 'Palkia',
    dexNumber: 484,
    types: ['Water', 'Dragon'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1dragon,@2dragon,@1fairy,@2fairy',
    featuredMonths: ['2026-02'],
    note: 'Dragon and Fairy equally effective. Same counters as Shadow Palkia.',
  },

  // ── Mega Raids ─────────────────────────────────────────────────────────────
  {
    id: 'mega-lucario',
    name: 'Mega Lucario',
    dexNumber: 448,
    types: ['Fighting', 'Steel'],
    category: 'Mega',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1fighting,@2fighting,@1ground,@2ground',
    note: 'Fire is best (Reshiram, Chandelure). Ground (Groudon) and Fighting (Conkeldurr) also strong.',
  },
  {
    id: 'mega-sceptile',
    name: 'Mega Sceptile',
    dexNumber: 254,
    types: ['Grass'],
    category: 'Mega',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Poison', multiplier: '1.6x' },
      { type: 'Flying', multiplier: '1.6x' },
      { type: 'Bug', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1ice,@2ice,@1flying,@2flying,@1poison,@2poison',
    featuredMonths: ['2026-07', '2026-01'],
    note: 'Many weaknesses. Fire and Ice are the strongest options (Reshiram, Mamoswine, Galarian Darmanitan).',
  },
  {
    id: 'mega-salamence',
    name: 'Mega Salamence',
    dexNumber: 373,
    types: ['Dragon', 'Flying'],
    category: 'Mega',
    weaknesses: [
      { type: 'Ice', multiplier: '2.56x' },
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1ice,@2ice,@1dragon,@2dragon,@1fairy,@2fairy,@1rock,@2rock',
    note: 'Double weak to Ice. Mamoswine, Galarian Darmanitan, and Glaceon are top picks. Dragon works but risky.',
  },
  {
    id: 'mega-aggron',
    name: 'Mega Aggron',
    dexNumber: 306,
    types: ['Steel'],
    category: 'Mega',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1fighting,@2fighting,@1ground,@2ground',
    note: 'Same weaknesses as Lucario. Reshiram, Groudon, Conkeldurr, Lucario all strong picks.',
  },

  // ── Dynamax (Max Mondays) ──────────────────────────────────────────────────
  {
    id: 'dynamax-chansey',
    name: 'Dynamax Chansey',
    dexNumber: 113,
    types: ['Normal'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Fighting', multiplier: '1.6x' },
    ],
    counterSearch: '@1fighting,@2fighting',
    note: 'Only weak to Fighting. Machamp, Lucario, Conkeldurr. Chansey is extremely bulky - bring your best.',
  },
  {
    id: 'dynamax-deino',
    name: 'Dynamax Deino',
    dexNumber: 633,
    types: ['Dark', 'Dragon'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Fairy', multiplier: '2.56x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Dragon', multiplier: '1.6x' },
    ],
    counterSearch: '@1fairy,@2fairy,@1fighting,@2fighting,@1ice,@2ice,@1dragon,@2dragon',
    note: 'Double weak to Fairy. Gardevoir, Togekiss, Sylveon demolish it. Fighting and Ice also strong.',
  },
  {
    id: 'dynamax-trubbish',
    name: 'Dynamax Trubbish',
    dexNumber: 568,
    types: ['Poison'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Psychic', multiplier: '1.6x' },
    ],
    counterSearch: '@1ground,@2ground,@1psychic,@2psychic',
    note: 'Ground and Psychic. Groudon, Garchomp, Mewtwo, Espeon all work well.',
  },
  {
    id: 'dynamax-feebas',
    name: 'Dynamax Feebas',
    dexNumber: 349,
    types: ['Water'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
    ],
    counterSearch: '@1electric,@2electric,@1grass,@2grass',
    note: 'Same as Kyogre counters - Electric and Grass. Zekrom, Kartana, Roserade.',
  },

  // ── Historical Tier 5 / Legendary Raids ─────────────────────────────────────
  {
    id: 'mewtwo',
    name: 'Mewtwo',
    dexNumber: 150,
    types: ['Psychic'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1ghost,@2ghost,@1dark,@2dark,@1bug,@2bug',
    note: 'Ghost and Dark are top picks. Gengar (Mega), Giratina Origin, Darkrai, Chandelure.',
  },
  {
    id: 'rayquaza',
    name: 'Rayquaza',
    dexNumber: 384,
    types: ['Dragon', 'Flying'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ice', multiplier: '2.56x' },
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1ice,@2ice,@1dragon,@2dragon,@1fairy,@2fairy,@1rock,@2rock',
    note: 'Double weak to Ice. Mamoswine, Galarian Darmanitan, Glaceon dominate.',
  },
  {
    id: 'groudon',
    name: 'Groudon',
    dexNumber: 383,
    types: ['Ground'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
    ],
    counterSearch: '@1water,@2water,@1grass,@2grass,@1ice,@2ice',
    featuredMonths: ['2026-04'],
    note: 'Water is best (Kyogre, Swampert). Grass and Ice also effective.',
  },
  {
    id: 'dialga',
    name: 'Dialga',
    dexNumber: 483,
    types: ['Steel', 'Dragon'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1fighting,@2fighting,@1ground,@2ground',
    featuredMonths: ['2026-02'],
    note: 'Only two weaknesses. Lucario, Conkeldurr, Groudon, Garchomp.',
  },
  {
    id: 'giratina-origin',
    name: 'Giratina (Origin)',
    dexNumber: 487,
    types: ['Ghost', 'Dragon'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1ghost,@2ghost,@1dragon,@2dragon,@1dark,@2dark,@1ice,@2ice,@1fairy,@2fairy',
    note: 'Many weaknesses. Gengar, Darkrai, Rayquaza, Garchomp all strong picks.',
  },
  {
    id: 'reshiram',
    name: 'Reshiram',
    dexNumber: 643,
    types: ['Dragon', 'Fire'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1dragon,@2dragon,@1ground,@2ground,@1rock,@2rock',
    note: 'Dragon and Ground are top. Garchomp, Dialga, Rayquaza, Rhyperior.',
  },
  {
    id: 'zekrom',
    name: 'Zekrom',
    dexNumber: 644,
    types: ['Dragon', 'Electric'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1dragon,@2dragon,@1ground,@2ground,@1ice,@2ice,@1fairy,@2fairy',
    note: 'Ground resists Electric. Garchomp, Groudon, Mamoswine, Dialga.',
  },
  {
    id: 'lugia',
    name: 'Lugia',
    dexNumber: 249,
    types: ['Psychic', 'Flying'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1electric,@2electric,@1dark,@2dark,@1ghost,@2ghost,@1ice,@2ice,@1rock,@2rock',
    note: 'Extremely bulky. Dark and Electric are safest. Darkrai, Zekrom, Raikou.',
  },
  {
    id: 'ho-oh',
    name: 'Ho-Oh',
    dexNumber: 250,
    types: ['Fire', 'Flying'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Rock', multiplier: '2.56x' },
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Water', multiplier: '1.6x' },
    ],
    counterSearch: '@1rock,@2rock,@1electric,@2electric,@1water,@2water',
    note: 'Double weak to Rock. Same counters as Moltres - Rampardos, Rhyperior, Tyranitar.',
  },
  {
    id: 'latios',
    name: 'Latios',
    dexNumber: 381,
    types: ['Dragon', 'Psychic'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1dragon,@2dragon,@1ghost,@2ghost,@1dark,@2dark,@1ice,@2ice,@1fairy,@2fairy',
    featuredMonths: ['2026-04'],
    note: 'Many weaknesses. Dragon and Ghost are fastest. Rayquaza, Gengar, Darkrai.',
  },
  {
    id: 'latias',
    name: 'Latias',
    dexNumber: 380,
    types: ['Dragon', 'Psychic'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1dragon,@2dragon,@1ghost,@2ghost,@1dark,@2dark,@1ice,@2ice,@1fairy,@2fairy',
    featuredMonths: ['2026-03'],
    note: 'Same typing as Latios but bulkier. Same counters apply.',
  },
  {
    id: 'heatran',
    name: 'Heatran',
    dexNumber: 485,
    types: ['Fire', 'Steel'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ground', multiplier: '2.56x' },
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
    ],
    counterSearch: '@1ground,@2ground,@1water,@2water,@1fighting,@2fighting',
    note: 'Double weak to Ground. Groudon, Garchomp, Excadrill, Rhyperior.',
  },
  {
    id: 'cresselia',
    name: 'Cresselia',
    dexNumber: 488,
    types: ['Psychic'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1ghost,@2ghost,@1dark,@2dark,@1bug,@2bug',
    featuredMonths: ['2026-05', '2026-01', '2024-09'],
    note: 'Very bulky. Dark is best - Darkrai, Tyranitar, Hydreigon. Gengar for speed.',
  },
  {
    id: 'regigigas',
    name: 'Regigigas',
    dexNumber: 486,
    types: ['Normal'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Fighting', multiplier: '1.6x' },
    ],
    counterSearch: '@1fighting,@2fighting',
    featuredMonths: ['2026-02'],
    note: 'Only weak to Fighting. Lucario, Conkeldurr, Machamp, Terrakion.',
  },
  {
    id: 'landorus-therian',
    name: 'Landorus (Therian)',
    dexNumber: 645,
    types: ['Ground', 'Flying'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ice', multiplier: '2.56x' },
      { type: 'Water', multiplier: '1.6x' },
    ],
    counterSearch: '@1ice,@2ice,@1water,@2water',
    note: 'Double weak to Ice. Mamoswine, Galarian Darmanitan, Glaceon. Water as backup.',
  },
  {
    id: 'tornadus-therian',
    name: 'Tornadus (Therian)',
    dexNumber: 641,
    types: ['Flying'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1electric,@2electric,@1ice,@2ice,@1rock,@2rock',
    note: 'Electric and Rock preferred. Zekrom, Rampardos, Rhyperior, Mamoswine.',
  },
  {
    id: 'thundurus-therian',
    name: 'Thundurus (Therian)',
    dexNumber: 642,
    types: ['Electric', 'Flying'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1ice,@2ice,@1rock,@2rock',
    note: 'Same typing as Zapdos. Mamoswine, Rhyperior, Rampardos.',
  },
  {
    id: 'xerneas',
    name: 'Xerneas',
    dexNumber: 716,
    types: ['Fairy'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Poison', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
    ],
    counterSearch: '@1poison,@2poison,@1steel,@2steel',
    note: 'Poison and Steel. Metagross (Meteor Mash), Roserade, Nihilego, Gengar.',
  },
  {
    id: 'yveltal',
    name: 'Yveltal',
    dexNumber: 717,
    types: ['Dark', 'Flying'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1fairy,@2fairy,@1electric,@2electric,@1rock,@2rock,@1ice,@2ice',
    note: 'Fairy resists both STAB types. Togekiss, Gardevoir, Zekrom, Rhyperior.',
  },
  {
    id: 'zacian',
    name: 'Zacian',
    dexNumber: 888,
    types: ['Fairy', 'Steel'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1ground,@2ground',
    featuredMonths: ['2026-03'],
    note: 'Only Fire and Ground. Reshiram, Groudon, Garchomp, Chandelure.',
  },
  {
    id: 'zamazenta',
    name: 'Zamazenta',
    dexNumber: 889,
    types: ['Fighting', 'Steel'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1ground,@2ground,@1fighting,@2fighting',
    featuredMonths: ['2026-03'],
    note: 'Same weaknesses as Lucario. Reshiram, Groudon, Conkeldurr.',
  },

  // ── Mythical Raids ─────────────────────────────────────────────────────────
  {
    id: 'darkrai',
    name: 'Darkrai',
    dexNumber: 491,
    types: ['Dark'],
    category: 'Mythical',
    weaknesses: [
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1fighting,@2fighting,@1fairy,@2fairy,@1bug,@2bug',
    note: 'Fighting is best. Lucario, Conkeldurr, Machamp. Togekiss for Fairy.',
  },
  {
    id: 'deoxys-normal',
    name: 'Deoxys (Normal)',
    dexNumber: 386,
    types: ['Psychic'],
    category: 'Mythical',
    weaknesses: [
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1ghost,@2ghost,@1dark,@2dark,@1bug,@2bug',
    note: 'Extremely fragile. Almost anything with Ghost/Dark moves can solo it.',
  },
  {
    id: 'genesect',
    name: 'Genesect',
    dexNumber: 649,
    types: ['Bug', 'Steel'],
    category: 'Mythical',
    weaknesses: [
      { type: 'Fire', multiplier: '2.56x' },
    ],
    counterSearch: '@1fire,@2fire',
    featuredMonths: ['2026-01'],
    note: 'Double weak to Fire (only weakness). Reshiram, Chandelure, Blaziken, Darmanitan.',
  },

  // ── Mega Raids (historical) ────────────────────────────────────────────────
  {
    id: 'mega-gengar',
    name: 'Mega Gengar',
    dexNumber: 94,
    types: ['Ghost', 'Poison'],
    category: 'Mega',
    weaknesses: [
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Psychic', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1ground,@2ground,@1ghost,@2ghost,@1psychic,@2psychic,@1dark,@2dark',
    note: 'Ground hits without taking Ghost damage back. Groudon, Garchomp, Mewtwo, Darkrai.',
  },
  {
    id: 'mega-charizard-y',
    name: 'Mega Charizard Y',
    dexNumber: 6,
    types: ['Fire', 'Flying'],
    category: 'Mega',
    weaknesses: [
      { type: 'Rock', multiplier: '2.56x' },
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Water', multiplier: '1.6x' },
    ],
    counterSearch: '@1rock,@2rock,@1electric,@2electric,@1water,@2water',
    note: 'Double weak to Rock. Same as Moltres/Ho-Oh counters.',
  },
  {
    id: 'mega-gyarados',
    name: 'Mega Gyarados',
    dexNumber: 130,
    types: ['Water', 'Dark'],
    category: 'Mega',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1electric,@2electric,@1grass,@2grass,@1fighting,@2fighting,@1fairy,@2fairy',
    note: 'Many weaknesses. Electric and Grass are most common strong picks.',
  },
  {
    id: 'mega-latios',
    name: 'Mega Latios',
    dexNumber: 381,
    types: ['Dragon', 'Psychic'],
    category: 'Mega',
    weaknesses: [
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1dragon,@2dragon,@1ghost,@2ghost,@1dark,@2dark,@1ice,@2ice,@1fairy,@2fairy',
    note: 'Same as regular Latios. Dragon and Ghost for speed, Dark for safety.',
  },
  {
    id: 'mega-rayquaza',
    name: 'Mega Rayquaza',
    dexNumber: 384,
    types: ['Dragon', 'Flying'],
    category: 'Mega',
    weaknesses: [
      { type: 'Ice', multiplier: '2.56x' },
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1ice,@2ice,@1dragon,@2dragon,@1fairy,@2fairy,@1rock,@2rock',
    note: 'Double weak to Ice. Same as regular Rayquaza - Mamoswine is king.',
  },
  {
    id: 'mega-garchomp',
    name: 'Mega Garchomp',
    dexNumber: 445,
    types: ['Dragon', 'Ground'],
    category: 'Mega',
    weaknesses: [
      { type: 'Ice', multiplier: '2.56x' },
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1ice,@2ice,@1dragon,@2dragon,@1fairy,@2fairy',
    note: 'Double weak to Ice. Mamoswine, Galarian Darmanitan, Glaceon. Fairy is safe backup.',
  },

  // ── April 2026 Tier 5 ────────────────────────────────────────────────────────
  // ── 2025 Historical Tier 5 ───────────────────────────────────────────────────
  {
    id: 'cobalion',
    name: 'Cobalion',
    dexNumber: 638,
    types: ['Steel', 'Fighting'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1fighting,@2fighting,@1ground,@2ground',
    featuredMonths: ['2025-11'],
    note: 'Same weaknesses as Lucario. Reshiram, Groudon, Conkeldurr.',
  },
  {
    id: 'terrakion',
    name: 'Terrakion',
    dexNumber: 639,
    types: ['Rock', 'Fighting'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Psychic', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1fighting,@2fighting,@1water,@2water,@1steel,@2steel,@1fairy,@2fairy,@1psychic,@2psychic',
    featuredMonths: ['2025-11'],
    note: 'Many weaknesses. Fighting is best (double resists Rock). Lucario, Conkeldurr, Metagross.',
  },
  {
    id: 'virizion',
    name: 'Virizion',
    dexNumber: 640,
    types: ['Grass', 'Fighting'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Flying', multiplier: '2.56x' },
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Poison', multiplier: '1.6x' },
      { type: 'Psychic', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1flying,@2flying,@1fire,@2fire,@1ice,@2ice,@1psychic,@2psychic,@1fairy,@2fairy',
    featuredMonths: ['2025-11'],
    note: 'Double weak to Flying. Rayquaza, Moltres, Honchkrow, Staraptor shred it.',
  },
  {
    id: 'necrozma-dusk-mane',
    name: 'Necrozma (Dusk Mane)',
    dexNumber: 800,
    types: ['Psychic', 'Steel'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1ground,@2ground,@1ghost,@2ghost,@1dark,@2dark',
    featuredMonths: ['2025-11'],
    note: 'Same typing as Solgaleo. Reshiram, Chandelure, Groudon, Darkrai.',
  },
  {
    id: 'necrozma-dawn-wings',
    name: 'Necrozma (Dawn Wings)',
    dexNumber: 800,
    types: ['Psychic', 'Ghost'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ghost', multiplier: '2.56x' },
      { type: 'Dark', multiplier: '2.56x' },
    ],
    counterSearch: '@1ghost,@2ghost,@1dark,@2dark',
    featuredMonths: ['2025-11'],
    note: 'Same typing as Lunala. Double weak to Ghost AND Dark. Gengar, Darkrai, Giratina Origin.',
  },

  // ── 2025 Historical Mega Raids ─────────────────────────────────────────────
  {
    id: 'mega-tyranitar',
    name: 'Mega Tyranitar',
    dexNumber: 248,
    types: ['Rock', 'Dark'],
    category: 'Mega',
    weaknesses: [
      { type: 'Fighting', multiplier: '2.56x' },
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1fighting,@2fighting,@1water,@2water,@1ground,@2ground,@1steel,@2steel,@1fairy,@2fairy',
    featuredMonths: ['2025-11'],
    note: 'Double weak to Fighting. Lucario, Conkeldurr, Machamp, Terrakion absolutely dominate.',
  },
  {
    id: 'mega-scizor',
    name: 'Mega Scizor',
    dexNumber: 212,
    types: ['Bug', 'Steel'],
    category: 'Mega',
    weaknesses: [
      { type: 'Fire', multiplier: '2.56x' },
    ],
    counterSearch: '@1fire,@2fire',
    featuredMonths: ['2025-10'],
    note: 'Double weak to Fire (only weakness). Same as Genesect - Reshiram, Chandelure, Blaziken.',
  },
  {
    id: 'mega-heracross',
    name: 'Mega Heracross',
    dexNumber: 214,
    types: ['Bug', 'Fighting'],
    category: 'Mega',
    weaknesses: [
      { type: 'Flying', multiplier: '2.56x' },
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Psychic', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1flying,@2flying,@1fire,@2fire,@1psychic,@2psychic,@1fairy,@2fairy',
    featuredMonths: ['2025-11'],
    note: 'Double weak to Flying. Rayquaza, Moltres, Honchkrow.',
  },
  {
    id: 'mega-beedrill',
    name: 'Mega Beedrill',
    dexNumber: 15,
    types: ['Bug', 'Poison'],
    category: 'Mega',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Flying', multiplier: '1.6x' },
      { type: 'Psychic', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1flying,@2flying,@1psychic,@2psychic,@1rock,@2rock',
    featuredMonths: ['2025-11'],
    note: 'Fire and Psychic preferred. Reshiram, Mewtwo, Moltres.',
  },
  {
    id: 'mega-mawile',
    name: 'Mega Mawile',
    dexNumber: 303,
    types: ['Steel', 'Fairy'],
    category: 'Mega',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1ground,@2ground',
    featuredMonths: ['2025-10'],
    note: 'Only Fire and Ground. Same as Zacian. Reshiram, Groudon, Garchomp.',
  },

  // ── GO Fest 2026 Global (July) ───────────────────────────────────────────────
  {
    id: 'mega-mewtwo-x',
    name: 'Mega Mewtwo X',
    dexNumber: 150,
    types: ['Psychic', 'Fighting'],
    category: 'Mega',
    weaknesses: [
      { type: 'Flying', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1ghost,@2ghost,@1flying,@2flying,@1fairy,@2fairy',
    featuredMonths: ['2026-07'],
    note: 'Ghost is best (immune to Fighting STAB). Gengar, Giratina Origin, Chandelure. Featured as Super Mega Raid at GO Fest 2026.',
  },
  {
    id: 'mega-abomasnow',
    name: 'Mega Abomasnow',
    dexNumber: 460,
    types: ['Grass', 'Ice'],
    category: 'Mega',
    weaknesses: [
      { type: 'Fire', multiplier: '2.56x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Flying', multiplier: '1.6x' },
      { type: 'Poison', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1fighting,@2fighting,@1flying,@2flying,@1steel,@2steel',
    featuredMonths: ['2026-07'],
    note: 'Double weak to Fire. Reshiram, Chandelure, Blaziken absolutely destroy it.',
  },
  {
    id: 'mega-swampert',
    name: 'Mega Swampert',
    dexNumber: 260,
    types: ['Water', 'Ground'],
    category: 'Mega',
    weaknesses: [
      { type: 'Grass', multiplier: '2.56x' },
    ],
    counterSearch: '@1grass,@2grass',
    featuredMonths: ['2026-07'],
    note: 'Double weak to Grass (only weakness). Kartana, Roserade, Sceptile, Zarude.',
  },
  {
    id: 'raikou',
    name: 'Raikou',
    dexNumber: 243,
    types: ['Electric'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1ground,@2ground',
    featuredMonths: ['2026-07'],
    note: 'Only weak to Ground. Groudon, Garchomp, Excadrill, Landorus.',
  },
  {
    id: 'entei',
    name: 'Entei',
    dexNumber: 244,
    types: ['Fire'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1water,@2water,@1ground,@2ground,@1rock,@2rock',
    featuredMonths: ['2026-07'],
    note: 'Water is best. Kyogre, Swampert, Kingler. Ground and Rock also work.',
  },
  {
    id: 'suicune',
    name: 'Suicune',
    dexNumber: 245,
    types: ['Water'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
    ],
    counterSearch: '@1electric,@2electric,@1grass,@2grass',
    featuredMonths: ['2026-07'],
    note: 'Very bulky. Electric and Grass - Zekrom, Kartana, Roserade.',
  },
  {
    id: 'uxie',
    name: 'Uxie',
    dexNumber: 480,
    types: ['Psychic'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1ghost,@2ghost,@1dark,@2dark,@1bug,@2bug',
    featuredMonths: ['2026-07'],
    note: 'Regional legendary (Asia-Pacific normally). Ghost and Dark best.',
  },
  {
    id: 'mesprit',
    name: 'Mesprit',
    dexNumber: 481,
    types: ['Psychic'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1ghost,@2ghost,@1dark,@2dark,@1bug,@2bug',
    featuredMonths: ['2026-07'],
    note: 'Regional legendary (Europe/Africa normally). Same counters as Uxie.',
  },
  {
    id: 'azelf',
    name: 'Azelf',
    dexNumber: 482,
    types: ['Psychic'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1ghost,@2ghost,@1dark,@2dark,@1bug,@2bug',
    featuredMonths: ['2026-07'],
    note: 'Regional legendary (Americas normally). Frailer than Uxie/Mesprit but same counters.',
  },
  {
    id: 'giratina-altered',
    name: 'Giratina (Altered)',
    dexNumber: 487,
    types: ['Ghost', 'Dragon'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1ghost,@2ghost,@1dragon,@2dragon,@1dark,@2dark,@1ice,@2ice,@1fairy,@2fairy',
    featuredMonths: ['2026-07'],
    note: 'Same typing as Origin but much bulkier. Dragon and Dark for speed, Fairy for safety.',
  },
  {
    id: 'zeraora',
    name: 'Zeraora',
    dexNumber: 807,
    types: ['Electric'],
    category: 'Mythical',
    weaknesses: [
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1ground,@2ground',
    featuredMonths: ['2026-07'],
    note: 'Only weak to Ground. Groudon, Garchomp, Excadrill. Available via GO Fest Special Research.',
  },

  // ── January 2026 Tier 5 ──────────────────────────────────────────────────────
  {
    id: 'blacephalon',
    name: 'Blacephalon',
    dexNumber: 806,
    types: ['Fire', 'Ghost'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1water,@2water,@1ground,@2ground,@1rock,@2rock,@1ghost,@2ghost,@1dark,@2dark',
    featuredMonths: ['2026-01'],
    note: 'Many weaknesses. Water and Ground safest. Kyogre, Groudon, Rhyperior, Darkrai.',
  },
  {
    id: 'thundurus-incarnate',
    name: 'Thundurus (Incarnate)',
    dexNumber: 642,
    types: ['Electric', 'Flying'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1ice,@2ice,@1rock,@2rock',
    featuredMonths: ['2026-01'],
    note: 'Same typing as Zapdos. Mamoswine, Rhyperior, Rampardos.',
  },
  {
    id: 'tornadus-incarnate',
    name: 'Tornadus (Incarnate)',
    dexNumber: 641,
    types: ['Flying'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1electric,@2electric,@1ice,@2ice,@1rock,@2rock',
    featuredMonths: ['2026-01'],
    note: 'Same as Therian forme. Electric and Rock preferred. Zekrom, Rampardos.',
  },

  // ── January 2026 Mega Raids ────────────────────────────────────────────────
  {
    id: 'mega-blaziken',
    name: 'Mega Blaziken',
    dexNumber: 257,
    types: ['Fire', 'Fighting'],
    category: 'Mega',
    weaknesses: [
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Flying', multiplier: '1.6x' },
      { type: 'Psychic', multiplier: '1.6x' },
    ],
    counterSearch: '@1water,@2water,@1ground,@2ground,@1flying,@2flying,@1psychic,@2psychic',
    featuredMonths: ['2026-01'],
    note: 'Water and Ground are safest. Kyogre, Groudon, Swampert, Mewtwo.',
  },
  {
    id: 'mega-ampharos',
    name: 'Mega Ampharos',
    dexNumber: 181,
    types: ['Electric', 'Dragon'],
    category: 'Mega',
    weaknesses: [
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1ground,@2ground,@1ice,@2ice,@1dragon,@2dragon,@1fairy,@2fairy',
    featuredMonths: ['2026-01'],
    note: 'Ground resists Electric STAB. Garchomp, Groudon, Mamoswine, Rayquaza.',
  },

  // ── January 2026 Dynamax ───────────────────────────────────────────────────
  {
    id: 'dynamax-drampa',
    name: 'Dynamax Drampa',
    dexNumber: 780,
    types: ['Normal', 'Dragon'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
    ],
    counterSearch: '@1ice,@2ice,@1dragon,@2dragon,@1fairy,@2fairy,@1fighting,@2fighting',
    featuredMonths: ['2026-01'],
    note: 'Ice and Fairy are safest. Mamoswine, Gardevoir, Togekiss.',
  },
  {
    id: 'dynamax-caterpie',
    name: 'Dynamax Caterpie',
    dexNumber: 10,
    types: ['Bug'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Flying', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1flying,@2flying,@1rock,@2rock',
    featuredMonths: ['2026-01'],
    note: 'Standard Bug weaknesses. Easy raid - any Fire attacker works.',
  },
  {
    id: 'dynamax-beldum',
    name: 'Dynamax Beldum',
    dexNumber: 374,
    types: ['Steel', 'Psychic'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1ground,@2ground,@1ghost,@2ghost,@1dark,@2dark',
    featuredMonths: ['2026-01'],
    note: 'Same typing as Solgaleo. Reshiram, Groudon, Darkrai, Chandelure.',
  },
  {
    id: 'dynamax-roggenrola',
    name: 'Dynamax Roggenrola',
    dexNumber: 524,
    types: ['Rock'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
    ],
    counterSearch: '@1water,@2water,@1fighting,@2fighting,@1ground,@2ground,@1grass,@2grass,@1steel,@2steel',
    featuredMonths: ['2026-01'],
    note: 'Many weaknesses. Water and Fighting most common picks.',
  },

  // ── March 2026 Tier 5 & earlier ──────────────────────────────────────────────
  {
    id: 'lunala',
    name: 'Lunala',
    dexNumber: 792,
    types: ['Psychic', 'Ghost'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ghost', multiplier: '2.56x' },
      { type: 'Dark', multiplier: '2.56x' },
    ],
    counterSearch: '@1ghost,@2ghost,@1dark,@2dark',
    featuredMonths: ['2026-02'],
    note: 'Double weak to Ghost AND Dark. Gengar, Darkrai, Giratina Origin, Chandelure absolutely shred it.',
  },

  // ── February 2026 Mega Raids ───────────────────────────────────────────────
  {
    id: 'mega-pidgeot',
    name: 'Mega Pidgeot',
    dexNumber: 18,
    types: ['Normal', 'Flying'],
    category: 'Mega',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1electric,@2electric,@1ice,@2ice,@1rock,@2rock',
    featuredMonths: ['2026-02'],
    note: 'Electric and Rock preferred. Zekrom, Rampardos, Rhyperior, Mamoswine.',
  },
  {
    id: 'mega-sableye',
    name: 'Mega Sableye',
    dexNumber: 302,
    types: ['Dark', 'Ghost'],
    category: 'Mega',
    weaknesses: [
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1fairy,@2fairy',
    featuredMonths: ['2026-02'],
    note: 'Only weak to Fairy. Gardevoir, Togekiss, Sylveon, Granbull.',
  },
  {
    id: 'mega-absol',
    name: 'Mega Absol',
    dexNumber: 359,
    types: ['Dark'],
    category: 'Mega',
    weaknesses: [
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1fighting,@2fighting,@1fairy,@2fairy,@1bug,@2bug',
    featuredMonths: ['2026-02'],
    note: 'Fighting is best. Lucario, Conkeldurr, Machamp. Very fragile - goes down fast.',
  },

  // ── February 2026 Dynamax ──────────────────────────────────────────────────
  {
    id: 'dynamax-wailmer',
    name: 'Dynamax Wailmer',
    dexNumber: 320,
    types: ['Water'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
    ],
    counterSearch: '@1electric,@2electric,@1grass,@2grass',
    featuredMonths: ['2026-02'],
    note: 'Standard Water weaknesses. Zekrom, Kartana, Roserade.',
  },
  {
    id: 'dynamax-machop',
    name: 'Dynamax Machop',
    dexNumber: 66,
    types: ['Fighting'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Flying', multiplier: '1.6x' },
      { type: 'Psychic', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1flying,@2flying,@1psychic,@2psychic,@1fairy,@2fairy',
    featuredMonths: ['2026-02'],
    note: 'Flying and Psychic preferred. Rayquaza, Mewtwo, Moltres, Gardevoir.',
  },

  {
    id: 'regieleki',
    name: 'Regieleki',
    dexNumber: 894,
    types: ['Electric'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1ground,@2ground',
    featuredMonths: ['2026-03'],
    note: 'Only weak to Ground. Groudon, Garchomp, Excadrill, Landorus.',
  },

  // ── March 2026 Mega Raids ──────────────────────────────────────────────────
  {
    id: 'mega-pinsir',
    name: 'Mega Pinsir',
    dexNumber: 127,
    types: ['Bug', 'Flying'],
    category: 'Mega',
    weaknesses: [
      { type: 'Rock', multiplier: '2.56x' },
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
    ],
    counterSearch: '@1rock,@2rock,@1fire,@2fire,@1electric,@2electric,@1ice,@2ice',
    featuredMonths: ['2026-03'],
    note: 'Double weak to Rock. Rampardos, Rhyperior, Tyranitar.',
  },
  {
    id: 'mega-steelix',
    name: 'Mega Steelix',
    dexNumber: 208,
    types: ['Steel', 'Ground'],
    category: 'Mega',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1water,@2water,@1fighting,@2fighting,@1ground,@2ground',
    featuredMonths: ['2026-03'],
    note: 'Fire and Water are best. Reshiram, Kyogre, Groudon, Lucario.',
  },
  {
    id: 'mega-slowbro',
    name: 'Mega Slowbro',
    dexNumber: 80,
    types: ['Water', 'Psychic'],
    category: 'Mega',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1electric,@2electric,@1grass,@2grass,@1ghost,@2ghost,@1dark,@2dark,@1bug,@2bug',
    featuredMonths: ['2026-03'],
    note: 'Many weaknesses. Electric and Dark are safest. Zekrom, Darkrai, Gengar.',
  },
  {
    id: 'mega-houndoom',
    name: 'Mega Houndoom',
    dexNumber: 229,
    types: ['Dark', 'Fire'],
    category: 'Mega',
    weaknesses: [
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1water,@2water,@1fighting,@2fighting,@1ground,@2ground,@1rock,@2rock',
    featuredMonths: ['2026-03'],
    note: 'Fighting is best (resists Dark). Lucario, Conkeldurr, Machamp, Terrakion.',
  },

  // ── March 2026 Dynamax ─────────────────────────────────────────────────────
  {
    id: 'dynamax-rookidee',
    name: 'Dynamax Rookidee',
    dexNumber: 821,
    types: ['Flying'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1electric,@2electric,@1ice,@2ice,@1rock,@2rock',
    featuredMonths: ['2026-03'],
    note: 'Standard Flying weaknesses. Zekrom, Rampardos, Mamoswine.',
  },
  {
    id: 'dynamax-falinks',
    name: 'Dynamax Falinks',
    dexNumber: 870,
    types: ['Fighting'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Flying', multiplier: '1.6x' },
      { type: 'Psychic', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1flying,@2flying,@1psychic,@2psychic,@1fairy,@2fairy',
    featuredMonths: ['2026-03'],
    note: 'Flying and Psychic preferred. Rayquaza, Mewtwo, Moltres, Gardevoir.',
  },
  {
    id: 'dynamax-regice',
    name: 'Dynamax Regice',
    dexNumber: 378,
    types: ['Ice'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1fighting,@2fighting,@1rock,@2rock,@1steel,@2steel',
    featuredMonths: ['2026-03'],
    note: 'Fire and Fighting best. Reshiram, Lucario, Conkeldurr, Metagross.',
  },
  {
    id: 'dynamax-woobat',
    name: 'Dynamax Woobat',
    dexNumber: 527,
    types: ['Psychic', 'Flying'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1electric,@2electric,@1dark,@2dark,@1ghost,@2ghost,@1ice,@2ice,@1rock,@2rock',
    featuredMonths: ['2026-03'],
    note: 'Many weaknesses. Dark and Electric are safest picks.',
  },

  // ── April 2026 Tier 5 ────────────────────────────────────────────────────────
  {
    id: 'regidrago',
    name: 'Regidrago',
    dexNumber: 895,
    types: ['Dragon'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Dragon', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1ice,@2ice,@1dragon,@2dragon,@1fairy,@2fairy',
    featuredMonths: ['2026-04', '2023-12'],
    note: 'Standard Dragon weaknesses. Mamoswine, Gardevoir, Rayquaza, Dialga.',
  },
  {
    id: 'tapu-koko',
    name: 'Tapu Koko',
    dexNumber: 785,
    types: ['Electric', 'Fairy'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Poison', multiplier: '1.6x' },
    ],
    counterSearch: '@1ground,@2ground,@1poison,@2poison',
    featuredMonths: ['2026-04', '2022-03'],
    note: 'Ground is best (immune to Electric STAB). Garchomp, Groudon, Excadrill.',
  },
  {
    id: 'tapu-lele',
    name: 'Tapu Lele',
    dexNumber: 786,
    types: ['Psychic', 'Fairy'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Poison', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
    ],
    counterSearch: '@1ghost,@2ghost,@1poison,@2poison,@1steel,@2steel',
    featuredMonths: ['2026-04', '2022-03'],
    note: 'Ghost and Steel preferred. Metagross, Gengar, Chandelure, Nihilego.',
  },

  // ── April 2026 Mega Raids ──────────────────────────────────────────────────
  {
    id: 'mega-manectric',
    name: 'Mega Manectric',
    dexNumber: 310,
    types: ['Electric'],
    category: 'Mega',
    weaknesses: [
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1ground,@2ground',
    featuredMonths: ['2026-04'],
    note: 'Only weak to Ground. Groudon, Garchomp, Excadrill, Landorus.',
  },
  {
    id: 'mega-aerodactyl',
    name: 'Mega Aerodactyl',
    dexNumber: 142,
    types: ['Rock', 'Flying'],
    category: 'Mega',
    weaknesses: [
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
    ],
    counterSearch: '@1water,@2water,@1electric,@2electric,@1steel,@2steel,@1ice,@2ice,@1rock,@2rock',
    featuredMonths: ['2026-04'],
    note: 'Many weaknesses. Water and Steel most common strong picks. Metagross, Kyogre.',
  },
  {
    id: 'mega-alakazam',
    name: 'Mega Alakazam',
    dexNumber: 65,
    types: ['Psychic'],
    category: 'Mega',
    weaknesses: [
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1ghost,@2ghost,@1dark,@2dark,@1bug,@2bug',
    featuredMonths: ['2026-04'],
    note: 'Ghost and Dark best. Gengar, Darkrai, Tyranitar, Chandelure.',
  },
  {
    id: 'mega-sharpedo',
    name: 'Mega Sharpedo',
    dexNumber: 319,
    types: ['Water', 'Dark'],
    category: 'Mega',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Bug', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1electric,@2electric,@1grass,@2grass,@1fighting,@2fighting,@1fairy,@2fairy',
    featuredMonths: ['2026-04'],
    note: 'Very fragile. Electric and Grass are fastest. Zekrom, Kartana, Lucario.',
  },
  {
    id: 'mega-banette',
    name: 'Mega Banette',
    dexNumber: 354,
    types: ['Ghost'],
    category: 'Mega',
    weaknesses: [
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Dark', multiplier: '1.6x' },
    ],
    counterSearch: '@1ghost,@2ghost,@1dark,@2dark',
    featuredMonths: ['2026-04'],
    note: 'Ghost and Dark. Gengar, Darkrai, Giratina Origin, Chandelure.',
  },

  // ── April 2026 Dynamax (Max Mondays) ───────────────────────────────────────
  {
    id: 'dynamax-trapinch',
    name: 'Dynamax Trapinch',
    dexNumber: 328,
    types: ['Ground'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
    ],
    counterSearch: '@1water,@2water,@1grass,@2grass,@1ice,@2ice',
    featuredMonths: ['2026-04'],
    note: 'Standard Ground weaknesses. Kyogre, Swampert, Mamoswine.',
  },
  {
    id: 'dynamax-drilbur',
    name: 'Dynamax Drilbur',
    dexNumber: 529,
    types: ['Ground'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
    ],
    counterSearch: '@1water,@2water,@1grass,@2grass,@1ice,@2ice',
    featuredMonths: ['2026-04'],
    note: 'Same as Trapinch. Water and Ice top picks.',
  },
  {
    id: 'dynamax-regirock',
    name: 'Dynamax Regirock',
    dexNumber: 377,
    types: ['Rock'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
    ],
    counterSearch: '@1water,@2water,@1fighting,@2fighting,@1ground,@2ground,@1grass,@2grass,@1steel,@2steel',
    featuredMonths: ['2026-04'],
    note: 'Many weaknesses. Water and Fighting best. Kyogre, Lucario, Conkeldurr.',
  },
  {
    id: 'dynamax-shuckle',
    name: 'Dynamax Shuckle',
    dexNumber: 213,
    types: ['Bug', 'Rock'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
    ],
    counterSearch: '@1water,@2water,@1rock,@2rock,@1steel,@2steel',
    featuredMonths: ['2026-04'],
    note: 'Insanely bulky but low attack. Water and Steel for consistent damage.',
  },

  // ── May 2026 Tier 5: Ultra Beasts & Tapus ───────────────────────────────────
  {
    id: 'nihilego',
    name: 'Nihilego',
    dexNumber: 793,
    types: ['Rock', 'Poison'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ground', multiplier: '2.56x' },
      { type: 'Psychic', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
      { type: 'Water', multiplier: '1.6x' },
    ],
    counterSearch: '@1ground,@2ground,@1psychic,@2psychic,@1steel,@2steel,@1water,@2water',
    featuredMonths: ['2026-05', '2022-06'],
    note: 'Double weak to Ground. Groudon, Garchomp, Excadrill dominate.',
  },
  {
    id: 'buzzwole',
    name: 'Buzzwole',
    dexNumber: 794,
    types: ['Bug', 'Fighting'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Flying', multiplier: '2.56x' },
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Psychic', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1flying,@2flying,@1fire,@2fire,@1psychic,@2psychic,@1fairy,@2fairy',
    featuredMonths: ['2026-05', '2022-06'],
    note: 'Double weak to Flying. Rayquaza, Moltres, Honchkrow, Staraptor.',
  },
  {
    id: 'pheromosa',
    name: 'Pheromosa',
    dexNumber: 795,
    types: ['Bug', 'Fighting'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Flying', multiplier: '2.56x' },
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Psychic', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1flying,@2flying,@1fire,@2fire,@1psychic,@2psychic,@1fairy,@2fairy',
    featuredMonths: ['2026-05', '2022-11'],
    note: 'Double weak to Flying. Same counters as Buzzwole but much more fragile.',
  },
  {
    id: 'xurkitree',
    name: 'Xurkitree',
    dexNumber: 796,
    types: ['Electric'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1ground,@2ground',
    featuredMonths: ['2026-05', '2022-11'],
    note: 'Only weak to Ground. Groudon, Garchomp, Excadrill, Landorus.',
  },
  {
    id: 'tapu-bulu',
    name: 'Tapu Bulu',
    dexNumber: 787,
    types: ['Grass', 'Fairy'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Poison', multiplier: '2.56x' },
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Flying', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
    ],
    counterSearch: '@1poison,@2poison,@1fire,@2fire,@1ice,@2ice,@1flying,@2flying,@1steel,@2steel',
    featuredMonths: ['2026-05', '2022-04'],
    note: 'Double weak to Poison. Roserade, Nihilego, Gengar with Sludge Bomb.',
  },
  {
    id: 'tapu-fini',
    name: 'Tapu Fini',
    dexNumber: 788,
    types: ['Water', 'Fairy'],
    category: 'Legendary',
    weaknesses: [
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Grass', multiplier: '1.6x' },
      { type: 'Poison', multiplier: '1.6x' },
    ],
    counterSearch: '@1electric,@2electric,@1grass,@2grass,@1poison,@2poison',
    featuredMonths: ['2026-05', '2022-11'],
    note: 'Electric and Grass preferred. Zekrom, Kartana, Roserade, Xurkitree.',
  },

  // ── May 2026 Mega Raids ────────────────────────────────────────────────────
  {
    id: 'mega-camerupt',
    name: 'Mega Camerupt',
    dexNumber: 323,
    types: ['Fire', 'Ground'],
    category: 'Mega',
    weaknesses: [
      { type: 'Water', multiplier: '2.56x' },
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1water,@2water,@1ground,@2ground',
    featuredMonths: ['2026-05'],
    note: 'Double weak to Water. Kyogre, Swampert, Kingler, Gyarados.',
  },
  {
    id: 'mega-glalie',
    name: 'Mega Glalie',
    dexNumber: 362,
    types: ['Ice'],
    category: 'Mega',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1fighting,@2fighting,@1rock,@2rock,@1steel,@2steel',
    featuredMonths: ['2026-05'],
    note: 'Fire and Fighting are best. Reshiram, Lucario, Conkeldurr, Metagross.',
  },
  {
    id: 'mega-altaria',
    name: 'Mega Altaria',
    dexNumber: 334,
    types: ['Dragon', 'Fairy'],
    category: 'Mega',
    weaknesses: [
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Poison', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1ice,@2ice,@1poison,@2poison,@1steel,@2steel,@1fairy,@2fairy',
    featuredMonths: ['2026-05'],
    note: 'Steel and Ice preferred. Metagross (Meteor Mash), Mamoswine, Dialga.',
  },
  {
    id: 'mega-medicham',
    name: 'Mega Medicham',
    dexNumber: 308,
    types: ['Fighting', 'Psychic'],
    category: 'Mega',
    weaknesses: [
      { type: 'Flying', multiplier: '1.6x' },
      { type: 'Ghost', multiplier: '1.6x' },
      { type: 'Fairy', multiplier: '1.6x' },
    ],
    counterSearch: '@1flying,@2flying,@1ghost,@2ghost,@1fairy,@2fairy',
    featuredMonths: ['2026-05'],
    note: 'Ghost is best - immune to Fighting STAB. Gengar, Chandelure, Giratina.',
  },

  // ── May 2026 Dynamax (Max Mondays) ─────────────────────────────────────────
  {
    id: 'dynamax-cottonee',
    name: 'Dynamax Cottonee',
    dexNumber: 546,
    types: ['Grass', 'Fairy'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Poison', multiplier: '2.56x' },
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
      { type: 'Flying', multiplier: '1.6x' },
      { type: 'Steel', multiplier: '1.6x' },
    ],
    counterSearch: '@1poison,@2poison,@1fire,@2fire,@1ice,@2ice,@1steel,@2steel',
    featuredMonths: ['2026-05'],
    note: 'Double weak to Poison. Same counters as Tapu Bulu.',
  },
  {
    id: 'dynamax-growlithe',
    name: 'Dynamax Growlithe',
    dexNumber: 58,
    types: ['Fire'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Water', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
      { type: 'Rock', multiplier: '1.6x' },
    ],
    counterSearch: '@1water,@2water,@1ground,@2ground,@1rock,@2rock',
    featuredMonths: ['2026-05', '2026-02'],
    note: 'Standard Fire weaknesses. Kyogre, Groudon, Rhyperior.',
  },
  {
    id: 'dynamax-registeel',
    name: 'Dynamax Registeel',
    dexNumber: 379,
    types: ['Steel'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Fighting', multiplier: '1.6x' },
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1fire,@2fire,@1fighting,@2fighting,@1ground,@2ground',
    featuredMonths: ['2026-05'],
    note: 'Same as Mega Aggron. Reshiram, Groudon, Lucario, Conkeldurr.',
  },
  {
    id: 'dynamax-combee',
    name: 'Dynamax Combee',
    dexNumber: 415,
    types: ['Bug', 'Flying'],
    category: 'Dynamax',
    weaknesses: [
      { type: 'Rock', multiplier: '2.56x' },
      { type: 'Fire', multiplier: '1.6x' },
      { type: 'Electric', multiplier: '1.6x' },
      { type: 'Ice', multiplier: '1.6x' },
    ],
    counterSearch: '@1rock,@2rock,@1fire,@2fire,@1electric,@2electric,@1ice,@2ice',
    featuredMonths: ['2026-05'],
    note: 'Double weak to Rock. Rampardos, Rhyperior, Tyranitar.',
  },

  // ── Other (kept from before) ───────────────────────────────────────────────
  {
    id: 'pikachu',
    name: 'Pikachu',
    dexNumber: 25,
    types: ['Electric'],
    category: 'Regular',
    weaknesses: [
      { type: 'Ground', multiplier: '1.6x' },
    ],
    counterSearch: '@1ground,@2ground',
    note: 'Only weak to Ground. Garchomp, Groudon, Excadrill, Landorus.',
  },
];
